EncryptDecrypt/urls.py

from django.conf.urls import url

from EncryptDecrypt import views


urlpatterns = [
     url(r'^$', views.viewlogin, name='index'),
  url(r'^Register/', views.viewRegister, name='register'),
    url(r'^RegisterAct/', views.register, name='registeract'),
     url(r'^LoginAct/', views.login, name='loginact'),
       url(r'^inbox/', views.inbox, name='inbox'),
      url(r'^Sentmail/', views.viewSentMail, name='sent'),
       url(r'^trash/', views.viewTrash, name='trash'),
        url(r'^compose/', views.viewCompose, name='compose'),
       url(r'^download/([^/]+)/$', views.downloader,name="downs"),
        url(r'^sendmail/', views.sendmail,name="composed"),
       url(r'^logut/', views.logout, name='logut'),
 
             
  
         
]

MusicalCryptography/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt

from EncryptDecrypt.views import home, viewlogin, login, register


urlpatterns = [
    url(r'^admin/', admin.site.urls),
            

   url(r'^', include('EncryptDecrypt.urls', namespace='login')),
]

EncryptDecrypt/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

EncryptDecrypt/views.py
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart

import smtplib



from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.models import User
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from EncryptDecrypt.read_email_user import read_email1, getconnection, \
    disconnect, downloaddata, writetoDict


# Create your views here.
def home(request):
    return render(request,"login.html",{})

def viewlogin(request):
    return render(request,"login.html",{})
def viewRegister(request):
    return render(request,"index.html",{})
def viewSentMail(request):
    mails=dict()
    datalist=list()
    conn=getconnection(request.session["username"], request.session["password"])
    ret = read_email1(conn,'[Gmail]/Sent Mail')
    for mailsdata in ret:
        mails["subject"]=mailsdata[0]
        mails["from"]=mailsdata[1]
        mails["mailtext"]=" ".join(mailsdata[3])
        if mailsdata[4]:
            mails["attachment"]=mailsdata[4]
        else:
            mails["attachment"]="None"
        datalist.append(mails.copy())  
    return render(request,"sentMail.html",{"mails":datalist,"user":request.session['user']})
def viewTrash(request):
    mails=dict()
    datalist=list()
    conn=getconnection(request.session["username"], request.session["password"])
    ret = read_email1(conn,'[Gmail]/Trash')
    for mailsdata in ret:
        mails["subject"]=mailsdata[0]
        mails["from"]=mailsdata[1]
        mails["mailtext"]=" ".join(mailsdata[3])
        if mailsdata[4]:
            mails["attachment"]=mailsdata[4]
        else:
            mails["attachment"]="None"
        datalist.append(mails.copy()) 
    return render(request,"trash.html",{"mails":datalist,"user":request.session['user']})

@csrf_exempt
def register(request):
 
    p=User.objects.create_user(email=request.POST.get('Email'),password=request.POST.get('pass', ''),username=request.POST.get('user', ''),is_active=1)
    p.save()
    return render(request,"login.html",{})

def downloader(request,file=None):
    if file=="None":
        return HttpResponse('sorry nothing to download')
        
    conn=getconnection(request.session["username"], request.session["password"])
    data=downloaddata(conn,file)
    return HttpResponse('File Downloaded to local folder and the message decoded as {}'.format(data))
  
def sendmail(request):
    to=request.POST.get('to')
    sender=request.POST.get('subject')
    message=request.POST.get('final_span')
    writetoDict(message)
    print to,sender,message
    recipients = [to] 
    emaillist = [elem.strip().split(',') for elem in recipients]
    msg = MIMEMultipart()
    msg['Subject'] = sender
    msg['From'] = request.session["username"]
    msg['Reply-to'] = request.session["username"]
    from enc import encrypt
    encrypt(10,message)
    
    msg.preamble = 'Multipart massage.\n'
     
    part = MIMEText("Hi, please find the attached file")
    msg.attach(part)
     
    part = MIMEApplication(open(str("new_songs.mid"),"rb").read())
    part.add_header('Content-Disposition', 'attachment', filename=str(len(message)))
    msg.attach(part)
     

    server = smtplib.SMTP("smtp.gmail.com:587")
    server.ehlo()
    server.starttls()
    server.login(request.session["username"],request.session["password"])
     
    server.sendmail(msg['From'], emaillist , msg.as_string())

    return HttpResponse('mail send with attachment')

def login(request):

    mails=dict()
    datalist=list()
    user=request.POST.get('username', '')
    Password=request.POST.get('password', '')
    request.session['user']=user
    data=User.objects.filter(username=user)
    for user in data:
        gmail_user=user.email
    import time
    request.session["username"]=gmail_user
    
    request.session["password"]=Password
    datatime=time.strftime("%H:%M:%S")
    conn=getconnection(gmail_user, Password)
    
    ret = read_email1(conn,'INBOX')
  
    for mailsdata in ret:
        mails["subject"]=mailsdata[0]
        mails["from"]=mailsdata[1]
        mails["mailtext"]=" ".join(mailsdata[3])
        if mailsdata[4]:
            mails["attachment"]=mailsdata[4]
        else:
            mails["attachment"]="None"
        datalist.append(mails.copy())   
    seo_specialist = authenticate(username=user, password=Password)
    if seo_specialist:
        print seo_specialist
        django_login(request,seo_specialist)
       
        return render(request,"inbox.html",{"mails":datalist,"user":user,"time":datatime})
    return render(request,"index.html",{})


def inbox(request):
    mails=dict()
    datalist=list()
    conn=getconnection(request.session["username"], request.session["password"])
    ret = read_email1(conn,'INBOX')
    for mailsdata in ret:
        mails["subject"]=mailsdata[0]
        mails["from"]=mailsdata[1]
        mails["mailtext"]=" ".join(mailsdata[3])
        if mailsdata[4]:
            mails["attachment"]=mailsdata[4]
        else:
            mails["attachment"]="None"
        
        datalist.append(mails.copy())   
    return render(request,"inbox.html",{"mails":datalist,"user":request.session['user']})


def viewCompose(request):
    return render(request,"compose.html",{})
def logout(request):
    
    
    conn=getconnection(request.session["username"], request.session["password"])
    disconnect(conn)
    django_logout(request)
    return render(request,"login.html",{})

EncryptDecrypt/crypto/templates/compose.html
{% load static %}
 
<!DOCTYPE html>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE"> 
        <title> Compose</title>
 <link rel="stylesheet" href="{% static 'data/css/bootstrap.css' %}">
        <script src="{% static 'data/js/voice.js' %}"></script>
        <!-- jQuery library -->
        <script src="{% static 'data/js/jquery.min.js' %}"></script>
        <!-- Latest compiled JavaScript -->
        <script src="{% static 'data/js/bootstrap.js' %}"></script>

    </head>
    <body >
       <div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-2">
            <div class="btn-group">
 <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                   Welcome {{user}}<span class="caret"></span>
                </button>
<!--                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Mail</a></li>
                    <li><a href="#">Contacts</a></li>
                    <li><a href="#">Tasks</a></li>
                </ul>-->
            </div>
        </div>
        <div class="col-sm-9 col-md-10">
            <!-- Split button -->
<!--            <div class="btn-group">
                <button type="button" class="btn btn-default">
                    <div class="checkbox" style="margin: 0;">
                        <label>
                            <input type="checkbox">
                        </label>
                    </div>
                </button>
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">All</a></li>
                    <li><a href="#">None</a></li>
                    <li><a href="#">Read</a></li>
                    <li><a href="#">Unread</a></li>
                    <li><a href="#">Starred</a></li>
                    <li><a href="#">Unstarred</a></li>
                </ul>
            </div>-->
            <button type="button" class="btn btn-default" data-toggle="tooltip" title="Refresh">
                &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-refresh"></span>&nbsp;&nbsp;&nbsp;</button>
            <!-- Single button -->
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    More <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Mark all as read</a></li>
                    <li class="divider"></li>
                    <li class="text-center"><small class="text-muted">Select messages to see more actions</small></li>
                </ul>
            </div>
            <div class="pull-right">
<!--                <span class="text-muted"><b>1</b>–<b>50</b> of <b>160</b></span>-->

                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </button>
                    <button type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-3 col-md-2">
             <li class="active"><a "{%url 'login:compose'%}" class="btn btn-danger btn-sm btn-block" role="button"><i class="glyphicon glyphicon-edit"></i> Compose</a> </li>
            <hr>
            <ul class="nav nav-pills nav-stacked">
<!--                <li class="active"><a href="#"><span class="badge pull-right">32</span> Inbox </a>
                </li>-->
   <a href="{%url 'login:inbox' %}"> Inbox </a>
                       
                        <!--                <li><a href="#">Starred</a></li>
                                        <li><a href="#">Important</a></li>-->
                        <li><a href="{%url 'login:sent'%}">Sent Mail</a></li>
                        <li><a href="{%url 'login:trash'%}">trash</a></li>
                        <li><a href="{%url 'login:logut'%}">logout</a></li>
<!--                <li><a href="#"><span class="badge pull-right">3</span>Drafts</a></li>-->
            </ul>
        </div>
        <div class="col-sm-9 col-md-10">
            <!-- Nav tabs -->
              
            <ul class="nav nav-tabs">
                <!-- <li class="active"> <a href="composeAction.jsp" class="btn btn-danger btn-sm btn-block" role="button"><i class="glyphicon glyphicon-edit"></i> Send</a></a></li> -->
<!--                <li><a href="#profile" data-toggle="tab"><span class="glyphicon glyphicon-user"></span>
                    Social</a></li>
                <li><a href="#messages" data-toggle="tab"><span class="glyphicon glyphicon-tags"></span>
                    Promotions</a></li>
                <li><a href="#settings" data-toggle="tab"><span class="glyphicon glyphicon-plus no-margin">
                </span></a></li>-->
            </ul>
            <!-- Tab panes -->
          
            <div class="tab-content">
                <div class="tab-pane fade in active" id="home">
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                         <form action="{%url 'login:composed' %}" id="b" name="b" method="post">
                         {% csrf_token %}
                             <span class="name" style="min-width: 120px;display: inline-block;">To:<input type="text" id="to" name="to" ></span>
                              <!-- <span class="name" style="min-width: 12px;display: inline-block;">LENGTH OF MESSAGE:<input type="text" id="length" name="length" ></span> -->
                                 
                             <span class="name" style="min-width: 120px;display: inline-block;">Subject:<input type="text" id="subject" name="subject" ></span> <br><br><br>
                                 
                             <span class="final" ><textarea cols="50" row="50" id="final_span" name="final_span" style="margin: 0px; width: 843px; height: 369px;"></textarea></span>
                              <span class="interim" id="interim_span"><input type="submit"  class="btn btn-danger" id="down" name="down" value="Sender" ></span><p></p>
 </form>
                                </a>
                    </div>
                </div>
              
                
            </div>
           
           
        </div>
    </div>
</div>

    </body>
  
</html>

EncryptDecrypt/crypto/templates/inbox.html
{% load static %}
<!DOCTYPE html>

<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
        <title> Vmail INBOX</title>
        <link rel="stylesheet" href="{% static 'data/css/bootstrap.css' %}">
        <script src="{% static 'data/js/voice.js' %}"></script>
        
     <style>
     #closes {
    display: -webkit-flex; /* Safari */
    -webkit-justify-content: space-around; /* Safari 6.1+ */
    display: flex;
    justify-content: space-around;
}
     </style>
        <!-- jQuery library -->
        <script src="{% static 'data/js/jquery.js' %}"></script>
        <!-- Latest compiled JavaScript -->
        <script src="{% static 'data/js/bootstrap.js' %}"></script>
         <!-- <script >
             
           $(document).ready(function() {
   $('a#close').hide();
  
    
    $('a#open').click(function() {

     $('a#close').toggle();
    });
});  
             
             
         </script> -->
       
    </head>
   
        <body>
            <div id="settings">
                .</div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-3 col-md-2">
                        <div class="btn-group">
                            <input type="hidden" id="data" > 
                            <button type="button" class="btn btn-primary dropdown-toggle " data-toggle="dropdown">
                                Welcome {{user}}<span class="caret"></span>
                        </button>
                        <!--                <ul class="dropdown-menu" role="menu">
                                            <li><a href="#">Mail</a></li>
                                            <li><a href="#">Contacts</a></li>
                                            <li><a href="#">Tasks</a></li>
                                        </ul>-->
                    </div>
                </div>
                <div class="col-sm-9 col-md-10">
            
                    <button type="button" class="btn btn-default" data-toggle="tooltip" title="Refresh">
                        &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-refresh"></span>&nbsp;&nbsp;&nbsp;</button>
                    <!-- Single button -->
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            More <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Mark all as read</a></li>
                            <li class="divider"></li>
                            <li class="text-center"><small class="text-muted">Select messages to see more actions</small></li>
                        </ul>
                    </div>
                    <div class="pull-right">
                        <!--                <span class="text-muted"><b>1</b>–<b>50</b> of <b>160</b></span>-->

                        <div class="btn-group btn-group-sm">
                            <button type="button" class="btn btn-default">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </button>
                            <button type="button" class="btn btn-default">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3 col-md-2">
                    <a href="{%url 'login:compose'%}" class="btn btn-danger btn-sm btn-block" role="button"><i class="glyphicon glyphicon-edit"></i> Compose</a>
                    <hr>
                    <ul class="nav nav-pills nav-stacked">
                        <!--                <li class="active"><a href="#"><span class="badge pull-right">32</span> Inbox </a>
                                        </li>-->
                        <li class="active"><a href="{%url 'login:inbox' %}"> Inbox </a>
                        </li>
                        <!--                <li><a href="#">Starred</a></li>
                                        <li><a href="#">Important</a></li>-->
                        <li><a href="{%url 'login:sent'%}">Sent Mail</a></li>
                        <li><a href="{%url 'login:trash'%}">trash</a></li>
                        <li><a href="{%url 'login:logut'%}">logout</a></li>

                        <!--                <li><a href="#"><span class="badge pull-right">3</span>Drafts</a></li>-->
                    </ul>
                </div>
                <div class="col-sm-9 col-md-10">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#home" data-toggle="tab"><span class="glyphicon glyphicon-inbox">
                                </span>Primary</a></li>
                        <!--                <li><a href="#profile" data-toggle="tab"><span class="glyphicon glyphicon-user"></span>
                                            Social</a></li>
                                        <li><a href="#messages" data-toggle="tab"><span class="glyphicon glyphicon-tags"></span>
                                            Promotions</a></li>
                                        <li><a href="#settings" data-toggle="tab"><span class="glyphicon glyphicon-plus no-margin">
                                        </span></a></li>-->
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="home">
                            <div class="list-group">
                           {% for mail in mails %}
                                <a href="#" class="list-group-item" id="open" style="background-color:#33b5e5">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox">
                                        </label>
                                        <span class="text-muted" style="font-size:20px;">
                                     {{mail.subject}}</span><br>
                                    </div>
                                     
                                </a>
                                        
                                        <div >
                                         <a href="#" class="list-group-item" id="close" >
                                    <span class="name" style="min-width: 120px;
                                                                                              display: inline-block;">FROM:
                                                                                              {{mail.from}}</span><br><br><br> <span  id="closes" class="">
                                                                                              {{mail.mailtext}}</span>
                                                                                           
                                                                                        
                                                                                                <span class="name" style="min-width: 20px;display: inline-block;">Attachment:<a href="{% url 'login:downs' mail.attachment %}" class="name"  >{{mail.attachment}}</a></span>
                                                                                     
                                    <span class="badge">{{time}}</span> 
                                    
                                    
                                    <span class="pull-right">
                                        
                                    <span  class="glyphicon glyphicon-paperclip">
                                          
                                            </span></span></a>
                                            
                                            <div>

                             {% endfor %}
                            </div>
                        </div>
                        <!-- <div class="tab-pane fade in" id="profile">
                            <div class="list-group">
                                <div class="list-group-item">
                                    <span class="text-center">This tab is empty.</span>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade in" id="messages">
                            ...</div>
                        <div class="tab-pane fade in" id="settings">
                            This tab is empty.</div>
                    </div> -->

                    <div class="row-md-12">

                        <!--                <div class="well"> 
                                          <a href="">Welcome</a>
                                        </div>-->

                    </div>
                </div>
            </div>
        </div>

    </body>
    

</html>

EncryptDecrypt/crypto/templates/sentMail.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title> Vmail Sent Items</title>
 <link rel="stylesheet" href="{% static 'data/css/bootstrap.css' %}">
        <script src="{% static 'data/js/voice.js' %}"></script>
        <!-- jQuery library -->
        <script src="{% static 'data/js/jquery.min.js' %}"></script>
        <!-- Latest compiled JavaScript -->
        <script src="{% static 'data/js/bootstrap.js' %}"></script>

   
    </head>
   
    <body >
       <div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-2">
            <div class="btn-group">
 <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                   Welcome {{user}}><span class="caret"></span>
 </button>

            </div>
        </div>
        <div class="col-sm-9 col-md-10">

            <button type="button" class="btn btn-default" data-toggle="tooltip" title="Refresh">
                &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-refresh"></span>&nbsp;&nbsp;&nbsp;</button>
            <!-- Single button -->
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    More <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Mark all as read</a></li>
                    <li class="divider"></li>
                    <li class="text-center"><small class="text-muted">Select messages to see more actions</small></li>
                </ul>
            </div>
            <div class="pull-right">
<!--                <span class="text-muted"><b>1</b>–<b>50</b> of <b>160</b></span>-->

                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </button>
                    <button type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-3 col-md-2">
            <a href="{%url 'login:compose'%}" class="btn btn-danger btn-sm btn-block" role="button"><i class="glyphicon glyphicon-edit"></i> Compose</a>
            <hr>
            <ul class="nav nav-pills nav-stacked">
<!--                <li class="active"><a href="#"><span class="badge pull-right">32</span> Inbox </a>
                </li>-->
   <li ><a href="{%url 'login:inbox' %}"> Inbox </a>
                        </li>
                        <!--                <li><a href="#">Starred</a></li>
                                        <li><a href="#">Important</a></li>-->
                        <li class="active"><a href="{%url 'login:sent'%}">Sent Mail</a></li>
                        <li><a href="{%url 'login:trash'%}">trash</a></li>
                        <li><a href="{%url 'login:logut'%}">logout</a></li>
            </ul>
        </div>
   <div class="col-sm-9 col-md-10">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#home" data-toggle="tab"><span class="glyphicon glyphicon-inbox">
                                </span>Primary</a></li>
                        <!--                <li><a href="#profile" data-toggle="tab"><span class="glyphicon glyphicon-user"></span>
                                            Social</a></li>
                                        <li><a href="#messages" data-toggle="tab"><span class="glyphicon glyphicon-tags"></span>
                                            Promotions</a></li>
                                        <li><a href="#settings" data-toggle="tab"><span class="glyphicon glyphicon-plus no-margin">
                                        </span></a></li>-->
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="home">
                            <div class="list-group">
                           {% for mail in mails %}
                                <a href="#" class="list-group-item" id="open" style="background-color:#33b5e5">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox">
                                        </label>
                                        <span class="text-muted" style="font-size:20px;">
                                     {{mail.subject}}</span><br>
                                    </div>
                                     
                                </a>
                                        
                                        <div >
                                         <a href="#" class="list-group-item" id="close" >
                                    <span class="name" style="min-width: 120px;
                                                                                              display: inline-block;">FROM:
                                                                                              {{mail.from}}</span><br><br><br> <span  id="closes" class="">
                                                                                              {{mail.mailtext}}</span>
                                                                                              
                                                                                               <span class="name" style="min-width: 20px;display: inline-block;">Attachment:<a href="#" class="name"  >{{mail.attachment}}</a></span>
                                    <span class="badge">{{time}}</span> <span class="pull-right"><span  class="glyphicon glyphicon-paperclip">
                                          
                                            </span></span></a>
                                            
                                            <div>

                             {% endfor %}
                            </div>
                        </div>
                        <!-- <div class="tab-pane fade in" id="profile">
                            <div class="list-group">
                                <div class="list-group-item">
                                    <span class="text-center">This tab is empty.</span>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade in" id="messages">
                            ...</div>
                        <div class="tab-pane fade in" id="settings">
                            This tab is empty.</div>
                    </div> -->

                    <div class="row-md-12">

                        <!--                <div class="well"> 
                                          <a href="">Welcome</a>
                                        </div>-->

                    </div>
                </div>
            </div>
        </div>


    </body>
    
</html>